kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: legacy-internal
spec:
  parentRefs:
  - kind: Gateway
    name: internal-http
  hostnames:
  - "legacy.example.com"
  - "legacy.agilework.info"
  rules:
  - backendRefs:
    - name: legacy
      port: 8080
  - matches:
    - path:
        value: /checkout
    backendRefs:
    - name: legacy-checkout
      port: 8080